@startuml

rectangle "bpmn-js" as bpmn
note left
    Отвечает за логику BPMN,
    строит диаграммы

    Валидирует действия пользователей,
    моделирует действия в соответствии
    с BPMN 2.0

    Предоставляет специфические
    действия BPMN
end note
rectangle "diagram-js" as diagram
note right
    Знает формы и соединения

    Предлагает расширяемую инфраструктуру
    модульных шаблонов, систему плагинов,
    шину событий, набор команд

    Включает в себя взаимодействие
    с пользователем: двигать, соединять,
    наводить, выбирать, добавлять, удалять
end note
rectangle "bpmn-moddle" as moddle
note left
    Читает / создает XML-файлы BPMN 2.0
    Предоставляет мета-модель BPMN
end note

bpmn --> moddle : << <b>use</b> >>
bpmn -> diagram : << <b>use</b> >>

@enduml